header:
  lang: fa
  slug: /product
  title: قابلیت‌ها
  desc: همه امکانات نرم‌افزاری که برای مدیریت تیم یا شرکت خود می‌خواهید، در یک طراحی قابل‌فهم و کاربردی. با ویژگی‌های تسکولو بیشتر آشنا شوید.
body:
  section1:
    header: مدیریت کار چند لایه و منعطف
    body: ساختار کاری خود را آن‌طور که راحت هستید بچینید. سازمان، پروژه، صفحه، لیست، کار و چک لیست تسکولو را تبدیل به منعطف‌ترین سیستم کار موجود کرده است.
  section2:
    header: ساده برای همه اعضای تیم
    body: همه می‌توانند با تسکولو کار کنند. فقط به هر نفر دسترسی به کارهایی بدهید که لازم دارد، کار را به کارشناسش بسپارید و خودتان نتیجه را ببینید.
  section3:
    header: افزایش بهره‌وری با تحلیل واقعی
    body: تحلیل‌گر تسکولو، تلاش‌های تیمی را تبدیل به داده‌های قابل تحلیل می‌کند. با گزارش‌های در لحظه، رسیدن به بهترین عملکرد را تبدیل به فرهنگ کاری خود خواهید کرد.
  features:
    -
      icon: fa-mobile
      title: کارها
      desc: به آسانی کار‌هایی که باید انجام شوند را ایجاد کنید و هیچ وقت آن‌ها را فراموش نکنید.
    -
      icon: fa-mobile
      title: پروژه‌ها
      desc: کارهای روزانه، پروژه‌محور یا فرآیندمحور خود را مطابق نیازهای کاری‌تان مرتب کنید و با تیم‌تان روی آن‌ها همکاری کنید.
    -
      icon: fa-mobile
      title: سازمان
      desc: مجموعه‌ای از پروژه‌های مرتبط را یک جا جمع کنید، مدیریت اعضای آن‌ها را متمرکز کرده و از امکانات تحلیل‌گر تسکولو برای آن‌ها استفاده نمایید.
    -
      icon: fa-mobile
      title: صفحه‌ها
      desc: بخش‌های مختلف یک پروژه پرجزییات {مُفصل} را از هم جدا کنید و نگران شلوغ شدن فضای کاری خود نباشید.
    -
      icon: fa-mobile
      title: لیست‌ها
      desc: با لیست‌ها فرآیندهای خود را تعریف کنید، جنبه‌های مختلف کارتان را مجزا کنید یا هرطور که می‌خواهید به پروژه خود ساختار دهید.
    -
      icon: fa-mobile
      title: بخش‌ها
      desc: مشخص کنید کارها در چه مرحله‌ای قرار دارند و همواره پیگیر وضعیت آن‌‌ها باشید.
    -
      icon: fa-mobile
      title: برچسب‌ها
      desc: به هر کار هر چند تا برچسب که می‌خواهید اختصاص دهید و به راحتی کارها را دسته‌بندی و فیلتر کنید.
    -
      icon: fa-mobile
      title: رنگ
      desc: اولویت کارها را تعیین کنید و در یک نگاه کارهای مهم را در فضای پروژه خود شناسایی یا در جستجوی پیشرفته فیلتر کنید.
    -
      icon: fa-mobile
      title: آپلود فایل‌ها و اسناد
      desc: همه فایل‌ها و اسناد مربوط را به کار ضمیمه کنید و با بقیه تیم به اشتراک بگذارید.
    -
      icon: fa-mobile
      title: پیش‌نمایش فایل‌ها
      desc: همه اسناد پروژه را بدون این‌که مرورگر را ترک کنید، هر جا که هستید ببینید.
    -
      icon: fa-mobile
      title: افزودن اعضا
      desc:
    -
      icon: fa-mobile
      title: واگذار کردن کارها به اعضا
      desc:
    -
      icon: fa-mobile
      title: کامنت روی کارها
      desc:
    -
      icon: fa-mobile
      title: تعیین سررسید
      desc:
    -
      icon: fa-mobile
      title: کپی‌کردن کارها
      desc:
    -
      icon: fa-mobile
      title: به اشتراک‌گذاری کارها
      desc:
    -
      icon: fa-mobile
      title: لیست انتخاب
      desc:
    -
      icon: fa-mobile
      title: بایگانی کارها
      desc:
    -
      icon: fa-mobile
      title: جستجوی پیشرفته در همه چیز
      desc:
    -
      icon: fa-mobile
      title: وارد کردن پروژه از ترلو
      desc:
    -
      icon: fa-mobile
      title: ایمیل‌های یادآوری
      desc:
    -
      icon: fa-mobile
      title: رمزگذاری دوطرفه
      desc:
    -
      icon: fa-mobile
      title: احراز هویت با موبایل
      desc:
    -
      icon: fa-mobile
      title: شخصی‌سازی تقویم و زبان
      desc:
    -
      icon: fa-mobile
      title: اپلیکیشن موبایل و دسکتاپ
      desc:
    -
      icon: fa-mobile
      title: اتاق‌های گفتگوی پروژه
      desc:
    -
      icon: fa-mobile
      title: ایجاد کار از پیام‌های اتاق
      desc:
    -
      icon: fa-mobile
      title: ثبت زمان‌های کاری
      desc:
    -
      icon: fa-mobile
      title: گزارش‌گیری از زمان‌های کاری
      desc:
    -
      icon: fa-mobile
      title: گزارش‌های هفتگی
      desc:
    -
      icon: fa-mobile
      title: تعریف تیم‌ها و دسترسی‌ها
      desc:
    -
      icon: fa-mobile
      title: پشتیبانی با اولویت بالا
      desc:
    -
      icon: fa-mobile
      title: نماینده موفقیت مشتری
      desc:
    -
      icon: fa-mobile
      title: پنل مدیریت
      desc:
    -
      icon: fa-mobile
      title: آنالیتیک
      desc: