header:
  lang: fa
  slug: /product
  title: قابلیت‌ها
  desc: همه امکانات نرم‌افزاری که برای مدیریت تیم یا شرکت خود می‌خواهید، در یک طراحی قابل‌فهم و کاربردی. با ویژگی‌های تسکولو بیشتر آشنا شوید.
body:
  hero:
    header: '[تَ سْ] (اسم) همه امکاناتی که برای مدیریت احتیاج دارید، با یک طراحی قابل فهم و زیبا'
  section1:
    header: مدیریت کار چند لایه و منعطف
    body: ساختار کاری خود را آن‌طور که راحت هستید بچینید. سازمان، پروژه، صفحه، لیست، کار و چک لیست تسکولو را تبدیل به منعطف‌ترین سیستم کار موجود کرده است.
  section2:
    header: ساده برای همه اعضای تیم
    body: همه می‌توانند با تسکولو کار کنند. فقط به هر نفر دسترسی به کارهایی بدهید که لازم دارد، کار را به کارشناسش بسپارید و خودتان نتیجه را ببینید.
  section3:
    header: افزایش بهره‌وری با تحلیل واقعی
    body: تحلیل‌گر تسکولو، تلاش‌های تیمی را تبدیل به داده‌های قابل تحلیل می‌کند. با گزارش‌های در لحظه، رسیدن به بهترین عملکرد را تبدیل به فرهنگ کاری خود خواهید کرد.
  features:
    header: همه امکانات تسکولو
    -
      icon: fa-mobile
      title: کارها
      desc: به آسانی کار‌هایی که باید انجام شوند را ایجاد کنید و هیچ وقت آن‌ها را فراموش نکنید.
    -
      icon: fa-mobile
      title: پروژه‌ها
      desc: کارهای روزانه، پروژه‌محور یا فرآیندمحور خود را مطابق نیازهای کاری‌تان مرتب کنید و با تیم‌تان روی آن‌ها همکاری کنید.
    -
      icon: fa-mobile
      title: سازمان
      desc: مجموعه‌ای از پروژه‌های مرتبط را یک جا جمع کنید، مدیریت اعضای آن‌ها را متمرکز کرده و از امکانات تحلیل‌گر تسکولو برای آن‌ها استفاده نمایید.
    -
      icon: fa-mobile
      title: صفحه‌ها
      desc: بخش‌های مختلف یک پروژه پرجزییات {مُفصل} را از هم جدا کنید و نگران شلوغ شدن فضای کاری خود نباشید.
    -
      icon: fa-mobile
      title: لیست‌ها
      desc: با لیست‌ها فرآیندهای خود را تعریف کنید، جنبه‌های مختلف کارتان را مجزا کنید یا هرطور که می‌خواهید به پروژه خود ساختار دهید.
    -
      icon: fa-mobile
      title: بخش‌ها
      desc: مشخص کنید کارها در چه مرحله‌ای قرار دارند و همواره پیگیر وضعیت آن‌‌ها باشید.
    -
      icon: fa-mobile
      title: برچسب‌ها
      desc: به هر کار هر چند تا برچسب که می‌خواهید اختصاص دهید و به راحتی کارها را دسته‌بندی و فیلتر کنید.
    -
      icon: fa-mobile
      title: رنگ
      desc: اولویت کارها را تعیین کنید و در یک نگاه کارهای مهم را در فضای پروژه خود شناسایی یا در جستجوی پیشرفته فیلتر کنید.
    -
      icon: fa-mobile
      title: آپلود فایل‌ها و اسناد
      desc: همه فایل‌ها و اسناد مربوط را به کار ضمیمه کنید و با بقیه تیم به اشتراک بگذارید.
    -
      icon: fa-mobile
      title: پیش‌نمایش فایل‌ها
      desc: همه اسناد پروژه را بدون این‌که مرورگر را ترک کنید، هر جا که هستید ببینید.
    -
      icon: fa-mobile
      title: افزودن اعضا
      desc: اعضای تیم خود را به پروژه‌ها و سازمان‌ها اضافه کنید و با همکاری نتیجه بگیرید.
    -
      icon: fa-mobile
      title: واگذار کردن کارها به اعضا
      desc: کار را به کارشناس‌هایش بسپارید تا همه بدانند چه کسی مسئول چه کاری است.
    -
      icon: fa-mobile
      title: کامنت روی کارها
      desc: در مورد ابهام‌ها و مشکلات روی کارها با هم صحبت کنید و زودتر کار را جلو ببرید.
    -
      icon: fa-mobile
      title: تعیین سررسید
      desc: تاریخ پایان هر کار را تعیین کنید، تا دیگر تاریخ‌های مهم پروژه در اوج کارها فراموش نشوند.
    -
      icon: fa-mobile
      title: کپی‌کردن کارها
      desc: کارهای تکراری و مشابه را یک بار بسازید و برای ساختن کار جدید از نمونه اصلی کپی بگیرید.
    -
      icon: fa-mobile
      title: به اشتراک‌گذاری کارها
      desc: کارها را با هر کس خواستید به اشتراک بگذارید، حتی اگر در پروژه نیستند.
    -
      icon: fa-mobile
      title: لیست انتخاب
      desc: برای کارهای چند مرحله‌ای، هر تعداد لیست انتخاب که خواستید تعریف کنید و از پیشرفت همه مرحله‌ها با خبر باشید.
    -
      icon: fa-mobile
      title: بایگانی کارها
      desc: میز کارتان را خلوت نگه دارید و همیشه به کارهای غیرضروری ولی مهم در بایگانی دسترسی داشته باشید.
    -
      icon: fa-mobile
      title: جستجوی پیشرفته در همه چیز
      desc: در همه چیز پروژه جستجو کنید و با فیلترهای پیشرفته هیچ وقت در پروژه‌های بزرگ خود چیزی را گم نکنید.
    -
      icon: fa-mobile
      title: وارد کردن پروژه از ترلو
      desc: مهاجرت از ترلو به تسکولو نه تنها انتخاب عاقلانه‌ای است، خیلی هم راحت است.
    -
      icon: fa-mobile
      title: ایمیل‌های یادآوری
      desc: قبل از اینکه سررسید به پایان برسد، ایمیل دریافت کنید و جلوی تاخیرها را بهتر بگیرید.
    -
      icon: fa-mobile
      title: رمزگذاری دوطرفه
      desc: تسکولو امنیت مدیریت پروژه را به مرحله جدیدی برده‌است. اطلاعات روی دستگاه شما رمزگذاری می‌شود و فقط روی دستگاه همکارانتان رمزگشایی می‌شود.
    -
      icon: fa-mobile
      title: احراز هویت با موبایل
      desc: اطلاعات حساس پروژه را با خیال راحت روی تسکولو نگاه دارید. هکرها حتا اگر به رمزعبور شما دست پیدا کنند، بدون موبایل شما نمی‌توانند به آن‌ها دست یابند.
    -
      icon: fa-mobile
      title: شخصی‌سازی تقویم و زبان
      desc: هر عضو پروژه می‌تواند زبان و تقویم نمایش خود را انتخاب کند. این یعنی همکاری راحت با همکارانتان در همه جای دنیا.
    -
      icon: fa-mobile
      title: اپلیکیشن موبایل و دسکتاپ
      desc: برای آندروید و iOS :)
    -
      icon: fa-mobile
      title: اتاق‌های گفتگوی پروژه
      desc: چت آنلاین به پیشرفت کارها سرعت بیشتری می‌دهد. اما چت کاری که با مدیریت کارها یکپارچه نباشد، نه چندان.
    -
      icon: fa-mobile
      title: ایجاد کار از پیام‌های اتاق
      desc: پیام که گرفتید خودش یک کار جدید بود؟ به راحتی آن را تبدیل به کار کنید، و در تسکولو مدیریتش کنید.
    -
      icon: fa-mobile
      title: ثبت زمان‌های کاری
      desc: همه زمان صرف شده روی پروژه خود را ثبت کنید و هزینه‌های نیروی انسانی را بهتر مدیریت کنید.
    -
      icon: fa-mobile
      title: گزارش‌گیری از زمان‌های کاری
      desc: زمان‌های کاری ثبت شده را براساس دوره زمانی و نفر فیلتر کنید و از آن‌ها خروجی اکسل بگیرید.
    -
      icon: fa-mobile
      title: گزارش‌های هفتگی
      desc: دورنمای مفیدی از پیشرفت پروژه و وضعیت اعضای پروژه در ایمیل‌های هفتگی جهت اطلاع مدیران عزیز پروژه.
    -
      icon: fa-mobile
      title: تعریف تیم‌ها و دسترسی‌ها
      desc: به جای ساختن چند پروژه کوچک و سخت کردن مدیریت، در یک پروژه به هر تیم فقط به صفحه‌ها و لیست‌های مختص خودش دسترسی بدهید.
    -
      icon: fa-mobile
      title: پشتیبانی با اولویت بالا
      desc: پشتیبانی تسکولو همیشه آماده است به شما کمک کند. اما گاهی جلوی صف بودن راحت‌تر است.
    -
      icon: fa-mobile
      title: نماینده موفقیت مشتری
      desc: کارشناس موفقیت مشتری به شما کمک می‌کند بیشترین استفاده را از تسکولو ببرید.
    -
      icon: fa-mobile
      title: پنل مدیریت
      desc: مدیریت پیشرفته اعضا و پروژه‌ها ویژه کاربران طرح اختصاصی
    -
      icon: fa-mobile
      title: تحلیل‌گر تسکولو
      desc: مدیریت عملکرد و بهره‌وری برای اساس داده‌های واقعی