--- 
header: 
  desc: "همه امکانات نرم‌افزاری که برای مدیریت تیم یا شرکت خود می‌خواهید، در یک طراحی قابل‌فهم و کاربردی. با ویژگی‌های تسکولو بیشتر آشنا شوید."
  lang: fa
  slug: /product
  title: قابلیت‌ها
body: 
  hero: 
    header: |
      <strong>تسکولو</strong>&nbsp;<em>/تَ سْ/</em><br/>
    desc: |
      (اسم) همه امکاناتی که برای مدیریت احتیاج دارید،<br/> با یک طراحی قابل فهم و زیبا
  section1: 
    body: "ساختار کاری خود را آن‌طور که راحت هستید بچینید. سازمان، پروژه، صفحه، لیست، کار و چک لیست تسکولو را تبدیل به منعطف‌ترین سیستم کار موجود کرده است."
    header: "مدیریت کار چند لایه و منعطف"
  section2: 
    body: "همه می‌توانند با تسکولو کار کنند. فقط به هر نفر دسترسی به کارهایی بدهید که لازم دارد، کار را به کارشناسش بسپارید و خودتان نتیجه را ببینید."
    header: "ساده برای همه اعضای تیم"
  section3: 
    body: "تحلیل‌گر تسکولو، تلاش‌های تیمی را تبدیل به داده‌های قابل تحلیل می‌کند. با گزارش‌های در لحظه، رسیدن به بهترین عملکرد را تبدیل به فرهنگ کاری خود خواهید کرد."
    header: "افزایش بهره‌وری با تحلیل واقعی"
  features: 
    header: "همه امکانات تسکولو"
    items: 
      - 
        desc: "به آسانی کار‌هایی که باید انجام شوند را ایجاد کنید و هیچ وقت آن‌ها را فراموش نکنید."
        icon: icon-tasks
        title: کارها
        link: "#"
      - 
        desc: "کارهای روزانه، پروژه‌محور یا فرآیندمحور خود را مطابق نیازهای کاری‌تان مرتب کنید و با تیم‌تان روی آن‌ها همکاری کنید."
        icon: icon-project
        title: پروژه‌ها
        link: ""
      - 
        desc: "مجموعه‌ای از پروژه‌های مرتبط را یک جا جمع کنید، مدیریت اعضای آن‌ها را متمرکز کرده و از امکانات تحلیل‌گر تسکولو برای آن‌ها استفاده نمایید."
        icon: icon-org
        title: سازمان
        link: ""
      - 
        desc: "بخش‌های مختلف یک پروژه پرجزییات {مُفصل} را از هم جدا کنید و نگران شلوغ شدن فضای کاری خود نباشید."
        icon: icon-sheets
        title: صفحه‌ها
        link: ""
      - 
        desc: "با لیست‌ها فرآیندهای خود را تعریف کنید، جنبه‌های مختلف کارتان را مجزا کنید یا هرطور که می‌خواهید به پروژه خود ساختار دهید."
        icon: icon-lists
        title: لیست‌ها
        link: ""
      - 
        desc: "مشخص کنید کارها در چه مرحله‌ای قرار دارند و همواره پیگیر وضعیت آن‌‌ها باشید."
        icon: icon-sections
        title: بخش‌ها
        link: ""
      - 
        desc: "به هر کار هر چند تا برچسب که می‌خواهید اختصاص دهید و به راحتی کارها را دسته‌بندی و فیلتر کنید."
        icon: icon-label
        title: برچسب‌ها
        link: ""
      - 
        desc: "اولویت کارها را تعیین کنید و در یک نگاه کارهای مهم را در فضای پروژه خود شناسایی یا در جستجوی پیشرفته فیلتر کنید."
        icon: icon-color
        title: رنگ
        link: ""
      - 
        desc: "همه فایل‌ها و اسناد مربوط را به کار ضمیمه کنید و با بقیه تیم به اشتراک بگذارید."
        icon: icon-upload
        title: "آپلود فایل‌ها و اسناد"
        link: ""
      - 
        desc: "همه اسناد پروژه را بدون این‌که مرورگر را ترک کنید، هر جا که هستید ببینید."
        icon: icon-preview
        title: "پیش‌نمایش فایل‌ها"
        link: ""
      - 
        desc: "اعضای تیم خود را به پروژه‌ها و سازمان‌ها اضافه کنید و با همکاری نتیجه بگیرید."
        icon: icon-add-member
        title: "افزودن اعضا"
        link: ""
      - 
        desc: "کار را به کارشناس‌هایش بسپارید تا همه بدانند چه کسی مسئول چه کاری است."
        icon: icon-assign-task
        title: "واگذار کردن کارها به اعضا"
        link: ""
      - 
        desc: "در مورد ابهام‌ها و مشکلات روی کارها با هم صحبت کنید و زودتر کار را جلو ببرید."
        icon: icon-task-comments
        title: "کامنت روی کارها"
        link: ""
      - 
        desc: "تاریخ پایان هر کار را تعیین کنید، تا دیگر تاریخ‌های مهم پروژه در اوج کارها فراموش نشوند."
        icon: icon-deadline
        title: "تعیین سررسید"
        link: ""
      - 
        desc: "کارهای تکراری و مشابه را یک بار بسازید و برای ساختن کار جدید از نمونه اصلی کپی بگیرید."
        icon: icon-copy-tasks
        title: "کپی‌کردن کارها"
        link: ""
      - 
        desc: "کارها را با هر کس خواستید به اشتراک بگذارید، حتی اگر در پروژه نیستند."
        icon: icon-share-task
        title: "به اشتراک‌گذاری کارها"
        link: ""
      - 
        desc: "برای کارهای چند مرحله‌ای، هر تعداد لیست انتخاب که خواستید تعریف کنید و از پیشرفت همه مرحله‌ها با خبر باشید."
        icon: icon-checklist
        title: "لیست انتخاب"
        link: ""
      - 
        desc: "میز کارتان را خلوت نگه دارید و همیشه به کارهای غیرضروری ولی مهم در بایگانی دسترسی داشته باشید."
        icon: icon-archive-tasks
        title: "بایگانی کارها"
        link: ""
      - 
        desc: "در همه چیز پروژه جستجو کنید و با فیلترهای پیشرفته هیچ وقت در پروژه‌های بزرگ خود چیزی را گم نکنید."
        icon: icon-search
        title: "جستجوی پیشرفته در همه چیز"
        link: ""
      - 
        desc: "مهاجرت از ترلو به تسکولو نه تنها انتخاب عاقلانه‌ای است، خیلی هم راحت است."
        icon: icon-trello
        title: "وارد کردن پروژه از ترلو"
        link: ""
      - 
        desc: "قبل از اینکه سررسید به پایان برسد، ایمیل دریافت کنید و جلوی تاخیرها را بهتر بگیرید."
        icon: icon-email-reminder
        title: "ایمیل‌های یادآوری"
        link: ""
      - 
        desc: "تسکولو امنیت مدیریت پروژه را به مرحله جدیدی برده‌است. اطلاعات روی دستگاه شما رمزگذاری می‌شود و فقط روی دستگاه همکارانتان رمزگشایی می‌شود."
        icon: icon-end2end
        title: "رمزگذاری دوطرفه"
        link: ""
      - 
        desc: "اطلاعات حساس پروژه را با خیال راحت روی تسکولو نگاه دارید. هکرها حتا اگر به رمزعبور شما دست پیدا کنند، بدون موبایل شما نمی‌توانند به آن‌ها دست یابند."
        icon: icon-mobile-auth
        title: "احراز هویت با موبایل"
        link: ""
      - 
        desc: "هر عضو پروژه می‌تواند زبان و تقویم نمایش خود را انتخاب کند. این یعنی همکاری راحت با همکارانتان در همه جای دنیا."
        icon: icon-custom-cal
        title: "شخصی‌سازی تقویم و زبان"
        link: ""
      - 
        desc: "برای آندروید و iOS :)"
        icon: icon-mobile-app
        title: "اپلیکیشن موبایل و دسکتاپ"
        link: ""
      - 
        desc: "چت آنلاین به پیشرفت کارها سرعت بیشتری می‌دهد. اما چت کاری که با مدیریت کارها یکپارچه نباشد، نه چندان."
        icon: icon-chat
        title: "اتاق‌های گفتگوی پروژه"
        link: ""
      - 
        desc: "پیام که گرفتید خودش یک کار جدید بود؟ به راحتی آن را تبدیل به کار کنید، و در تسکولو مدیریتش کنید."
        icon: icon-make-task
        title: "ایجاد کار از پیام‌های اتاق"
        link: ""
      - 
        desc: "همه زمان صرف شده روی پروژه خود را ثبت کنید و هزینه‌های نیروی انسانی را بهتر مدیریت کنید."
        icon: icon-timelog
        title: "ثبت زمان‌های کاری"
        link: ""
      - 
        desc: "زمان‌های کاری ثبت شده را براساس دوره زمانی و نفر فیلتر کنید و از آن‌ها خروجی اکسل بگیرید."
        icon: icon-reports
        title: "گزارش‌گیری از زمان‌های کاری"
        link: ""
      - 
        desc: "دورنمای مفیدی از پیشرفت پروژه و وضعیت اعضای پروژه در ایمیل‌های هفتگی جهت اطلاع مدیران عزیز پروژه."
        icon: icon-weekly-reports
        title: "گزارش‌های هفتگی"
        link: ""
      - 
        desc: "به جای ساختن چند پروژه کوچک و سخت کردن مدیریت، در یک پروژه به هر تیم فقط به صفحه‌ها و لیست‌های مختص خودش دسترسی بدهید."
        icon: icon-team-access
        title: "تعریف تیم‌ها و دسترسی‌ها"
        link: ""
      - 
        desc: "پشتیبانی تسکولو همیشه آماده است به شما کمک کند. اما گاهی جلوی صف بودن راحت‌تر است."
        icon: icon-support
        title: "پشتیبانی با اولویت بالا"
        link: ""
      - 
        desc: "کارشناس موفقیت مشتری به شما کمک می‌کند بیشترین استفاده را از تسکولو ببرید."
        icon: icon-success
        title: "نماینده موفقیت مشتری"
        link: ""
      - 
        desc: "مدیریت پیشرفته اعضا و پروژه‌ها ویژه کاربران طرح اختصاصی"
        icon: icon-admin-panel
        title: "پنل مدیریت"
        link: ""
      - 
        desc: "مدیریت عملکرد و بهره‌وری برای اساس داده‌های واقعی"
        icon: icon-analytics
        title: "تحلیل‌گر تسکولو"
        link: ""
...
